import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { interviewApi } from '../../services/interviewApi';
import Modal from '../../components/common/Modal';
export default function CompanyInterviews() {
  const [items, setItems] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState(''), [selected, setSelected] = useState(null), [form, setForm] = useState({}), [busy, setBusy] = useState(false);
  async function load() { setLoading(true); try { const r = await interviewApi.list(); setItems(r.data.items); } catch(e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  function edit(item) { setError(''); setSelected(item); setForm({ status: item.status, result: item.result, feedback: item.feedback || '' }); }
  async function save(event) { event.preventDefault(); setBusy(true); setError(''); try { await interviewApi.update(selected._id, form); await load(); setSelected(null); setNotice('Interview outcome saved. Application decisions are managed separately.'); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-5xl space-y-5"><h1 className="text-3xl font-semibold">Interviews</h1><p className="text-sm text-slate-600">Review scheduled interviews and record outcomes. <Link className="text-blue-700 underline" to="/company/applications">Schedule from an application</Link>.</p>{error && !selected && <p role="alert" className="text-red-700">{error}</p>}{notice && <p role="status">{notice}</p>}{loading ? <p>Loading interviews…</p> : <div className="divide-y border-y border-slate-200">{items.map(item => <section key={item._id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><h2 className="font-semibold">{item.candidate?.user?.firstName} {item.candidate?.user?.lastName} · {item.job?.title}</h2><p className="mt-1 text-sm">{item.round} · {item.scheduledAt ? new Date(item.scheduledAt).toLocaleString() : 'Time not set'} · {item.status} · {item.result}</p>{item.feedback && <p className="mt-2 whitespace-pre-wrap text-sm">{item.feedback}</p>}{item.meetingLink && <a className="mt-2 block text-sm text-blue-700 underline" href={item.meetingLink} target="_blank" rel="noopener noreferrer">Meeting link</a>}</div><button className="btn-ghost border" type="button" onClick={() => edit(item)}>Record outcome</button></section>)}{!items.length && <p className="py-6 text-sm">No interviews scheduled.</p>}</div>}<Modal open={Boolean(selected)} title="Record interview outcome" onClose={() => { if (!busy) setSelected(null); }}><form className="space-y-4" onSubmit={save}>{error && <p role="alert" className="text-red-700">{error}</p>}<label className="block">Status<select className="input" value={form.status || 'scheduled'} onChange={e => setForm({...form,status:e.target.value})}>{['scheduled','completed','cancelled','no_show'].map(s => <option key={s} value={s}>{s.replace('_',' ')}</option>)}</select></label><label className="block">Result<select className="input" value={form.result || 'pending'} onChange={e => setForm({...form,result:e.target.value})}>{['pending','pass','fail','hold'].map(s => <option key={s}>{s}</option>)}</select></label><label className="block">Feedback<textarea className="input" rows={4} maxLength={5000} value={form.feedback || ''} onChange={e => setForm({...form,feedback:e.target.value})} /></label><button type="submit" disabled={busy} className="btn-primary">{busy ? 'Saving…' : 'Save outcome'}</button></form></Modal></div>;
}
