import { useEffect, useState } from 'react';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';
export default function StudentDigitalCard() {
  const { user } = useAuth(); const [student, setStudent] = useState(null); const [error, setError] = useState('');
  useEffect(() => { let active = true; api.get('/students/me').then(r => { if (active) setStudent(r.data.student); }).catch(e => { if (active) setError(e.message || 'Unable to load digital card.'); }); return () => { active = false; }; }, []);
  function printCard() {
    const card = document.getElementById('student-digital-card'); if (!card) return;
    const frame = document.createElement('iframe'); frame.title = 'Print student digital card'; frame.style.position = 'fixed'; frame.style.width = '0'; frame.style.height = '0'; document.body.appendChild(frame);
    const doc = frame.contentDocument; doc.open(); doc.write('<!doctype html><html><head><title>SkillSetu Student Card</title><style>body{font:16px Arial;padding:32px;color:#182d37}article{border:1px solid #bbb;padding:28px;max-width:560px}h3{font-size:24px}p{line-height:1.6}small{display:block;margin-top:24px}</style></head><body></body></html>'); doc.close(); doc.body.appendChild(card.cloneNode(true)); frame.contentWindow.focus(); frame.contentWindow.print(); setTimeout(() => frame.remove(), 60000);
  }
  return <section aria-label="Student digital card" className="border-y border-slate-200 py-6"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-xl font-semibold">Student digital card</h2>{student && <button type="button" onClick={printCard} className="rounded border border-slate-300 px-4 py-2 text-sm">Print / Save PDF</button>}</div>{error && <p role="alert" className="mt-4 text-red-700">{error}</p>}{!student && !error && <p className="mt-4 text-sm">Loading card…</p>}{student && <article id="student-digital-card" className="mt-4 max-w-xl border border-slate-300 bg-white p-6"><p className="text-sm font-semibold tracking-wide">SKILLSETU · STUDENT CARD</p><h3 className="mt-4 text-2xl font-semibold">{user?.firstName} {user?.lastName}</h3><p className="mt-2 text-sm">{student.university?.name || 'Institution not linked'}</p><p className="mt-1 text-sm">{student.department?.name || 'Department not linked'}{student.batch ? ` · ${student.batch}` : ''}</p>{student.enrollmentNo && <p className="mt-2 text-sm">Enrollment: {student.enrollmentNo}</p>}<p className="mt-4 break-all font-mono text-xs">STU-{String(student._id).toUpperCase()}</p><p className="mt-3 text-sm">Account linked · {student.privacy?.showProfile === false ? 'Profile private' : 'Profile visible to platform recruiters'}</p><small className="mt-5 block text-xs text-slate-500">Platform identifier. This card is not an institution-issued ID or identity verification. Competency evidence is available in the authenticated profile.</small></article>}</section>;
}
