import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../services/api';
export default function StudentSettings() {
  const [privacy, setPrivacy] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { api.get('/students/me').then(r => setPrivacy({ showProfile: r.data.student.privacy?.showProfile !== false, showScores: r.data.student.privacy?.showScores !== false })).catch(e => setError(e.message)); }, []);
  async function save(e) { e.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await api.patch('/students/me', { privacy }); setMessage('Visibility settings saved.'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-4xl p-6"><h1 className="text-3xl font-semibold">Account settings</h1><p className="mt-2 text-sm text-slate-600">Manage recruiter access to your profile and evidence. Your institution’s TPO retains institutional access.</p>{error && <p role="alert" className="mt-4 text-red-700">{error}</p>}{message && <p role="status" className="mt-4 text-green-800">{message}</p>}{privacy && <form onSubmit={save} className="mt-6 space-y-5 border-y py-6"><label className="flex gap-3 text-sm"><input type="checkbox" checked={privacy.showProfile} onChange={e => setPrivacy({ ...privacy, showProfile: e.target.checked })} />Show my profile in recruiter discovery</label><label className="flex gap-3 text-sm"><input type="checkbox" checked={privacy.showScores} onChange={e => setPrivacy({ ...privacy, showScores: e.target.checked })} />Show my scores and competency evidence to recruiters</label><p className="text-xs text-slate-500">Applications and work already submitted to a company remain part of that company’s records.</p><button disabled={busy} className="rounded border border-slate-300 px-4 py-2 text-sm">Save visibility settings</button></form>}<Link className="mt-6 inline-block text-sm text-blue-700 underline" to="/student/profile">Edit personal details and view digital card</Link></main>;
}
