import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../services/api';
export default function StudentSettings() {
  const [privacy, setPrivacy] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { api.get('/students/me').then(r => setPrivacy({ showProfile: r.data.student.privacy?.showProfile !== false, showScores: r.data.student.privacy?.showScores !== false })).catch(e => setError(e.message)); }, []);
  async function save(e) { e.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await api.patch('/students/me', { privacy }); setMessage('Visibility settings saved.'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <div className="student-settings-page"><div className="student-settings-container"><header className="student-settings-header"><div><p className="student-eyebrow">Student workspace · Account</p><h1>Privacy and visibility</h1><p>Choose what recruiters can discover while your institution retains its placement access.</p></div></header>{error && <p role="alert" className="student-settings-error">{error}</p>}{message && <p role="status" className="student-settings-success">{message}</p>}{privacy && <form onSubmit={save} className="student-settings-form"><div className="student-settings-option"><label><input type="checkbox" checked={privacy.showProfile} onChange={e => setPrivacy({ ...privacy, showProfile: e.target.checked })} /><span><strong>Show my profile in recruiter discovery</strong><small>Let companies find your public student profile when they search for talent.</small></span></label></div><div className="student-settings-option"><label><input type="checkbox" checked={privacy.showScores} onChange={e => setPrivacy({ ...privacy, showScores: e.target.checked })} /><span><strong>Show my scores and competency evidence to recruiters</strong><small>Share recorded evidence with recruiters. This does not turn it into a certification.</small></span></label></div><p className="student-settings-note">Applications and work already submitted to a company remain part of that company&apos;s records. Your institution&apos;s TPO retains institutional access.</p><button disabled={busy} className="btn btn-primary" type="submit">{busy ? 'Saving…' : 'Save visibility settings'}</button></form>}<Link className="student-settings-profile-link" to="/student/profile">Edit personal details and view Digital Card <span aria-hidden="true">→</span></Link></div></div>;
}
