const router = require('express').Router();
const { z } = require('zod');
const { authMiddleware } = require('../../middleware/auth.middleware');
const { requireRoles } = require('../../middleware/role.middleware');
const { asyncHandler } = require('../../middleware/asyncHandler');
const { validate } = require('../../middleware/validation.middleware');
const { success } = require('../../utils/response');
const service = require('./challenge.service');
const text = z.string().trim().min(1);
const createBody = z.object({ title: text.max(120), brief: text.min(30).max(5000), skill: text.max(80), expectedHours: z.number().min(0.5).max(8), deadline: z.string().datetime(), rubric: z.array(z.object({ criterion: text.max(120), weight: z.number().min(1).max(100) }).strict()).min(1).max(8) }).strict().refine(b => b.rubric.reduce((sum, r) => sum + r.weight, 0) === 100, 'Rubric weights must total 100').refine(b => new Set(b.rubric.map(r => r.criterion.toLowerCase())).size === b.rubric.length, 'Criteria must be distinct');
const submissionBody = z.object({ url: z.string().url().max(2000).refine(u => /^https:\/\//i.test(u), 'Use an HTTPS link'), rationale: text.min(30).max(5000) }).strict();
const reviewBody = z.object({ scores: z.array(z.number().min(0).max(100)).min(1).max(8), feedback: text.min(10).max(3000) }).strict();
const schema = body => z.object({ body });
router.use(authMiddleware, requireRoles('student', 'recruiter', 'tpo'));
router.get('/', asyncHandler(async (req, res) => success(res, 'OK', await service.list(req.user))));
router.post('/', requireRoles('recruiter'), validate(schema(createBody)), asyncHandler(async (req, res) => success(res, 'Challenge created', { item: await service.create(req.user.id, req.validated.body) }, 201)));
router.post('/:id/close', requireRoles('recruiter'), asyncHandler(async (req, res) => success(res, 'Challenge closed', { item: await service.close(req.user.id, req.params.id) })));
router.post('/:id/submissions', requireRoles('student'), validate(schema(submissionBody)), asyncHandler(async (req, res) => success(res, 'Submitted', { item: await service.submit(req.user.id, req.params.id, req.validated.body) }, 201)));
router.get('/:id/submissions', requireRoles('recruiter', 'tpo'), asyncHandler(async (req, res) => success(res, 'OK', { items: await service.submissions(req.user, req.params.id) })));
router.post('/:id/submissions/:submissionId/review', requireRoles('recruiter'), validate(schema(reviewBody)), asyncHandler(async (req, res) => success(res, 'Review recorded', { item: await service.review(req.user.id, req.params.id, req.params.submissionId, req.validated.body) })));
module.exports = router;
module.exports.createBody = createBody;
