import { useEffect, useState } from 'react';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import Button from '../../components/common/Button';
const defaultRubric = [{ criterion: 'Problem understanding', weight: 25 }, { criterion: 'Solution quality', weight: 35 }, { criterion: 'Trade-off reasoning', weight: 25 }, { criterion: 'Communication', weight: 15 }];
const inputClass = 'w-full rounded border border-slate-300 px-3 py-2 text-sm';
export default function ChallengesPage() {
  const { user } = useAuth(); const company = user.role === 'recruiter'; const student = user.role === 'student';
  const [data, setData] = useState(null); const [selected, setSelected] = useState(null); const [submissions, setSubmissions] = useState([]);
  const [creating, setCreating] = useState(false); const [form, setForm] = useState({ title: '', brief: '', skill: '', expectedHours: 2, deadline: '' });
  const [work, setWork] = useState({ url: '', rationale: '' }); const [review, setReview] = useState(null); const [scores, setScores] = useState([]); const [feedback, setFeedback] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function load() { const r = await api.get('/challenges'); setData(r.data); }
  useEffect(() => { load().catch(e => setError(e.message || 'Unable to load challenges.')); }, []);
  async function open(item) {
    setBusy(true); setError(''); setSelected(null); setReview(null); setWork({ url: '', rationale: '' });
    try { if (!student) { const r = await api.get(`/challenges/${item._id}/submissions`); setSubmissions(r.data.items); } setSelected(item); } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  async function action(fn, success) { setBusy(true); setError(''); setMessage(''); try { await fn(); await load(); setMessage(success); } catch (e) { setError(e.message || 'Unable to save.'); } finally { setBusy(false); } }
  async function create(e) { e.preventDefault(); await action(async () => { await api.post('/challenges', { ...form, expectedHours: Number(form.expectedHours), deadline: new Date(form.deadline).toISOString(), rubric: defaultRubric }); setCreating(false); }, 'Challenge created.'); }
  async function submit(e) { e.preventDefault(); await action(async () => { await api.post(`/challenges/${selected._id}/submissions`, work); setSelected(null); }, 'Submission saved. Your evidence will appear after review.'); }
  async function saveReview(e) { e.preventDefault(); await action(async () => { await api.post(`/challenges/${selected._id}/submissions/${review._id}/review`, { scores: scores.map(Number), feedback }); const r = await api.get(`/challenges/${selected._id}/submissions`); setSubmissions(r.data.items); setReview(null); }, 'Review recorded and competency evidence linked.'); }
  const mine = selected && data?.submissions?.find(s => s.challenge === selected._id);
  return <main className="mx-auto max-w-6xl p-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">Company challenges</h1><p className="mt-2 text-sm text-slate-600">Focused anonymized briefs, bounded effort, and transparent rubric reviews.</p></div>{company && <Button onClick={() => { setCreating(true); setSelected(null); }}>Create challenge</Button>}</header>{error && <p role="alert" className="mt-4 text-red-700">{error}</p>}{message && <p role="status" className="mt-4 text-green-800">{message}</p>}{!data && !error && <p className="mt-6">Loading challenges…</p>}
    {creating && <form onSubmit={create} className="mt-6 max-w-3xl space-y-4 border-y border-slate-200 py-6"><h2 className="text-xl font-semibold">New challenge</h2><p className="text-sm text-slate-500">Remove client names and confidential information. Use a learning brief rather than production work.</p>{[['title', 'Title'], ['skill', 'Skill assessed']].map(([key, label]) => <label className="block text-sm" key={key}>{label}<input required maxLength={key === 'title' ? 120 : 80} className={`${inputClass} mt-1`} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<label className="block text-sm">Anonymized brief<textarea required minLength={30} maxLength={5000} rows={5} className={`${inputClass} mt-1`} value={form.brief} onChange={e => setForm({ ...form, brief: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Expected effort (hours)<input required type="number" min="0.5" max="8" step="0.5" className={`${inputClass} mt-1`} value={form.expectedHours} onChange={e => setForm({ ...form, expectedHours: e.target.value })} /></label><label className="text-sm">Deadline (your local time)<input required type="datetime-local" className={`${inputClass} mt-1`} value={form.deadline} onChange={e => setForm({ ...form, deadline: e.target.value })} /></label></div><h3 className="font-medium">Review rubric</h3>{defaultRubric.map(r => <p className="flex justify-between text-sm" key={r.criterion}><span>{r.criterion}</span><span>{r.weight}%</span></p>)}<div className="flex gap-3"><Button disabled={busy} type="submit">Publish challenge</Button><Button type="button" variant="ghost" disabled={busy} onClick={() => setCreating(false)}>Cancel</Button></div></form>}
    {selected && <section className="mt-6 border-y border-slate-200 py-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-semibold">{selected.title}</h2><Button variant="ghost" disabled={busy} onClick={() => { setSelected(null); setReview(null); }}>Back to list</Button></div><p className="mt-2 text-sm text-slate-500">{selected.skill} · {selected.expectedHours} hours · Due {new Date(selected.deadline).toLocaleString()} · {selected.status}</p><p className="mt-5 whitespace-pre-wrap text-sm leading-6">{selected.brief}</p><div className="mt-5 space-y-2">{selected.rubric.map(r => <p key={r._id || r.criterion} className="text-sm">{r.criterion} · {r.weight}%</p>)}</div>
      {student && (mine ? <div className="mt-6 border-t pt-4"><h3 className="font-medium">Your submission · {mine.status}</h3><a className="mt-2 block text-sm text-blue-700 underline" href={mine.url} target="_blank" rel="noopener noreferrer">Open submitted work</a>{mine.review?.evaluatedAt && <><p className="mt-2 text-sm">Score {mine.review.score}% · {new Date(mine.review.evaluatedAt).toLocaleDateString()}</p><p className="mt-2 whitespace-pre-wrap text-sm">{mine.review.feedback}</p></>}</div> : selected.status === 'open' && new Date(selected.deadline) > new Date() ? <form onSubmit={submit} className="mt-6 max-w-2xl space-y-4 border-t pt-5"><h3 className="font-semibold">Submit your work</h3><p className="text-sm text-slate-500">One final submission. Use an accessible HTTPS link without confidential information.</p><label className="block text-sm">Work link<input required type="url" maxLength={2000} className={`${inputClass} mt-1`} value={work.url} onChange={e => setWork({ ...work, url: e.target.value })} /></label><label className="block text-sm">Approach and trade-offs<textarea required minLength={30} maxLength={5000} rows={5} className={`${inputClass} mt-1`} value={work.rationale} onChange={e => setWork({ ...work, rationale: e.target.value })} /></label><Button disabled={busy} type="submit">Submit final work</Button></form> : <p className="mt-5 text-sm">Submissions closed.</p>)}
      {!student && <div className="mt-6 border-t pt-5"><h3 className="font-semibold">{company ? 'Submissions' : 'Submissions from your institution'}</h3>{!submissions.length && <p className="mt-3 text-sm text-slate-500">No submissions yet.</p>}{submissions.map(s => <div key={s._id} className="mt-4 border-b pb-4"><div className="flex flex-wrap justify-between gap-3"><span>{s.student?.user?.firstName} {s.student?.user?.lastName} · {s.status}</span>{company && s.status !== 'reviewed' && <Button disabled={busy} onClick={() => { setReview(s); setScores(selected.rubric.map(() => '')); setFeedback(''); }}>Review</Button>}</div><a href={s.url} target="_blank" rel="noopener noreferrer" className="mt-2 block text-sm text-blue-700 underline">Open submitted work</a><p className="mt-2 whitespace-pre-wrap text-sm">{s.rationale}</p>{s.status === 'reviewed' && <p className="mt-2 text-sm">{s.review.score}% · {s.review.feedback}</p>}</div>)}</div>}
      {review && <form onSubmit={saveReview} className="mt-6 max-w-2xl space-y-4"><h3 className="font-semibold">Final rubric review</h3><p className="text-sm text-slate-500">This review cannot be edited after saving.</p>{selected.rubric.map((r, i) => <label key={r._id || i} className="block text-sm">{r.criterion} ({r.weight}% weight)<input required type="number" min="0" max="100" className={`${inputClass} mt-1`} value={scores[i]} onChange={e => setScores(scores.map((s, j) => j === i ? e.target.value : s))} /></label>)}<label className="block text-sm">Feedback<textarea required minLength={10} maxLength={3000} rows={4} className={`${inputClass} mt-1`} value={feedback} onChange={e => setFeedback(e.target.value)} /></label><Button disabled={busy} type="submit">Record final review</Button></form>}
      {company && selected.status === 'open' && <Button variant="ghost" className="mt-6" disabled={busy} onClick={() => action(async () => { await api.post(`/challenges/${selected._id}/close`); setSelected({ ...selected, status: 'closed' }); }, 'Challenge closed to new submissions.')}>Close submissions</Button>}
    </section>}
    {!selected && !creating && data && <div className="mt-6 divide-y border-t border-slate-200">{data.items.map(item => <section key={item._id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><h2 className="font-semibold">{item.title}</h2><p className="mt-1 text-sm text-slate-500">{item.skill} · {item.expectedHours} hours · Due {new Date(item.deadline).toLocaleDateString()} · {item.status === 'open' && new Date(item.deadline) > new Date() ? 'Open' : 'Closed'}</p></div><Button disabled={busy} variant="ghost" onClick={() => open(item)}>View brief{!student ? ' & submissions' : ''}</Button></section>)}{!data.items.length && <p className="py-6 text-sm text-slate-500">No company challenges yet.</p>}<p className="pt-5 text-xs text-slate-500">Latest 100 challenges. Company reviews record rubric evaluations; they are not independent certifications.</p></div>}
  </main>;
}
